---
title: "Project R"
output: html_notebook
Lily Lopez
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(prophet)
```


```{r}
##upload dataset
bitcoin <-read.csv(file = '~/Desktop/R_project_bitcoin/BTC-USD.csv', stringsAsFactors = F)
```


```{r}
#check for missing values
sum(is.na(bitcoin))
```

```{r}
str(bitcoin)
```


```{r}
summary(bitcoin)
```
```{r}

bitcoin %>%
  filter(Volume == max(Volume))
```

```{r}
#format Date column
bitcoin$Date <- ymd(bitcoin$Date)
```


```{r}
head(bitcoin)
```


```{r}

bitcoin %>%
  filter(Date == '2021-04-13')
```

```{r}
#Plot Close price
qplot(Date, Close, data = bitcoin, 
      main = "Bitcoin closing prices 2014-2022")
```

```{r}
#log transformation
ds <- bitcoin$Date
y <- log(bitcoin$Close)
df <- data.frame(ds, y)
```

```{r}
#Plot Close price in log scale
qplot(ds, y, data = df, 
      main = "Bitcoin closing prices in log scale")
```

```{r}
# Built a forecasting model
m <- prophet(df)
```

```{r}
str(m)
```
```{r}
#add a number of days to forecast
future <- make_future_dataframe(m, periods = 365)
tail(future)
```
```{r}
#forecast
forecast <- predict(m, future)
```

```{r}
#plot forecast
plot(m, forecast)
dyplot.prophet(m, forecast)
exp(11.36)
prophet_plot_components(m, forecast)
```
```{r}
#model performance
str(forecast)
pred <- forecast$yhat[1:2747]
actual <- m$history$y
plot(actual, pred)
abline(lm(pred~actual), col = 'red')
```

```{r}
head(df)
```
```{r}
summary(lm(pred~actual))
```
```{r}
x <- cross_validation(m, 365, units = 'days')
performance_metrics(x, rolling_window = 0.1) #10%
plot_cross_validation_metric(x, metric = 'rmse', #mae
                             rolling_window = 0.1)
```
```{r}
#Reference: 
#Dr. Bharatendra Ra: "Forecasting cryptocurrency Ethereum prices with R | Application of Time-Series Analysis" https://www.youtube.com/watch?v=rV-hhKBRKbI
```

