
#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)
library(shinythemes)
library(lubridate)
library(dygraphs)
library(xts)
library(prophet)
library(tidyverse)
library(ggplot2)
library(gridExtra)

bitcoin <-read.csv(file = 'BTC-USD.csv', stringsAsFactors = F)
bitcoin$Date <- ymd(bitcoin$Date)


freq_per_year <-read.csv(file = 'freq_per_year.csv', stringsAsFactors = F)
replies_count <-read.csv(file = 'replies_count.csv', stringsAsFactors = F)
retweet_count <-read.csv(file = 'retweet_count.csv', stringsAsFactors = F)
likes_count <-read.csv(file = 'likes_count.csv', stringsAsFactors = F)


bitcoin_tweets_positive <-read.csv(file = 'bitcoin_tweets_positive.csv', stringsAsFactors = F)
bitcoin_tweets_positive$Date <- ymd(bitcoin_tweets_positive$Date)


bitcoin_tweets_negative <-read.csv(file = 'bitcoin_tweets_negative.csv', stringsAsFactors = F)
bitcoin_tweets_negative$Date <- ymd(bitcoin_tweets_negative$Date)

bitcoin_tweets_neutral<-read.csv(file = 'bitcoin_tweets_neutral.csv', stringsAsFactors = F)
bitcoin_tweets_neutral$Date <- ymd(bitcoin_tweets_neutral$Date)




# Define UI for application that draws a histogram
ui <- navbarPage(
  theme = shinytheme("cosmo"),
  h1(strong("Bitcoin Analysis")), 
  
  tabPanel(h3("Introduction"),
           sidebarLayout(
             sidebarPanel(
               (img(src = "https://www.goldandsilver.org/wp-content/uploads/2020/06/What-is-Bitcoin-Definition-of-Bitcoin.jpg", width = "100%")),
               p("The above image is from: https://www.goldandsilver.org/wp-content/uploads/2020/06/What-is-Bitcoin-Definition-of-Bitcoin.jpg")
             
      ),       
          
          
          mainPanel(
             h2(strong("Presentation Overview")),
             h3("- Research Objective/Target Audience"),
             h3("- Bitcoin Brief Overview"),
             h3("- Bitcoin Analysis"),
             h3("- Bitcoin Forecast"),
             h3("- Elon Musk's Twitter Account Analysis"),
             h3("- Elon Musk Tweets and Bitcoin Prices"),
             h3("- Conclusion, Recommendation, Future work"),
             br(),
             br(),
             h2(strong("Research objective:")),
             h3("Analyzing, predicting bitcoin prices, and identifying if Elon Musk's tweets had any impact on bitcoin price"), 
             br(),
             h2(strong("Target audience:")),
             h3("Anyone interested in investing in Bitcoin"), 
        
            )
          )
      ),
  
  
  tabPanel(h3("Bitcoin Overview"),
           sidebarLayout(
             sidebarPanel(
               (img(src = "https://i.etsystatic.com/24689880/r/il/bfafe0/3207238407/il_570xN.3207238407_iico.jpg", width = "100%")),
               p("The above image is from: https://i.etsystatic.com/24689880/r/il/bfafe0/3207238407/il_570xN.3207238407_iico.jpg")
               
             ),       
             
             
             mainPanel(
               h2(strong("Definition")),
               h3("\"Bitcoin is a type of digital currency in which a record of transactions is maintained and new units of currency are generated by the computational solution of mathematical problems, and which operates independently of a central bank.\""),              
               h3("\ - Oxford Languages"),
               br(),
               h2(strong("About Bitcoin")),
               h3("-first introduced in 2008 as a decentralized currency by Satoshi Nakamoto"), 
               h3("-cryptocurrency uses public-key cryptography to record, sign and send transactions over the Bitcoin blockchain"),
               h3("-the most popular cryptocurrency in the world, it has inspired the development of many other cryptocurrencies"),
               br(),
               br()
               
               
             )
           )
  ),
  
  
  
 
  tabPanel(h3("Bitcoin Dashboard"),
           sidebarLayout(
             sidebarPanel(
               h4(strong("Dataset")),
               p("\ - data.frame: dataset is collected from Kaggle.com"),
               p("\ - data.frame: 2747 observations, 7 variables"),
               p("\ - data.frame: from 2014-09-17 to 2022-03-25"),
               p("\ - data.frame: no missing values"),
               br(),
               h4(strong("Bitcoin closing prices 2014-2022")),
               br(),
               selectInput('selectOutput', 
                           'Select output', 
                           choices = colnames(bitcoin)[c(2,3,4,5,7)]),
               dateRangeInput('selectDate', 
                              'Select date', 
                              start = min(bitcoin$Date), 
                              end = max(bitcoin$Date)),
               br(),
               br(),
               checkboxInput("logInput", "Plot y axis on log scale", value = FALSE),
               h4(strong("Key Takeaways")),
               p("\ - Bitcoin has increased its trading volume; it peaked on Feb 26, 2021, with a total volume of 350.97 billion"),
               p("\ - historical prices have been volatile over the years; it has gone through several bubbles; 
                 min Close price is $178.10 on Jan 14, 2015, and the max Close price is $67,566.83 on Nov 8, 2021"),
               p("\ - overall trend: prices are going up")
               
            ),
             
               
             mainPanel(dygraphOutput("priceGraph", width = "100%", height = "800px"))
           )
  ),
  
  tabPanel(h3("Bitcoin Forecast"), 
           sidebarLayout(
             sidebarPanel(
               h4(strong("Bitcoin Price Forecast")),
               p("\ - Facebook's prophet library"),
               p("\ - forecasting time series data based on an additive model where non-linear trends are fit with yearly, weekly, and daily seasonality, plus holiday effects"),
               p("\ - add 365 days to predict, forecast's end date is Mar 25, 2023"),
               br(),
               br(),
               br(),
               h4(strong("Bitcoin closing prices 2014-2023")),
               br(),
               h5(strong("Choose the number of days to forecast")),
               selectInput('selectVariable', 'Select variable', choices = colnames(bitcoin)[c(2,3,4,5)]), 
               sliderInput("selectHorizon",label="How many days to predict?",min=1,max=365,value=1),
               h5(strong("Explaination")),
               checkboxInput("logInput2", "Plot y axis on log scale", value = FALSE),
               h4(strong("Conclusion")),
               p("\ - prediction based on prophet library didn't work for bitcoin; need to look into other variables that might impact the price")
               
             ),
             
             mainPanel(dygraphOutput("BitcoinForecast",height = "500px"))
           
           
            )
  ),

  tabPanel(h3("Elon Musk and Twitter"),
         sidebarLayout(
           sidebarPanel(
             h4(strong("Dataset")),
             p("\ - data.frame: datasets are collected from Kaggle.com"),
             p("\ - data.frame: 15897 observations, 15 variables"),
             p("\ - data.frame: from 2010-06-04 to 2022-03-05"),
             p("\ - data.frame: date, tweet, replies_count, retweet_counts, likes"),
             br(),
             h4(strong("Elon Musk Tweet Analysis")),
             p("-tweet count evolution: Elon Musk started actively using Twitter in 2015 -2016"),
             p("-increased popularity over years: number of replies, retweets, likes peaked in 2021"),
             br(),
             br(),
             br()
           
             
           ),
           mainPanel(
                     plotOutput("gmplot")
          )
       )
  ),



  tabPanel(h3("Elon Musk Tweets and Bitcoin Prices"),
         sidebarLayout(
           sidebarPanel(
             h4(strong("Elon Musk Tweets")),
             h5(strong("Positive Tweets:")),
             p("\ - Date: December 20, 2020: \"Bitcoin is almost as bs as fiat money\" SC = -.02"),
             p("\ - Date: December 20, 2020: \"Bitcoin is my safe word\" SC = .33"),
             p("\ - Date: February 7, 2021: \"@itsALLrisky It’s the most fun crypto!\" SC = .51"),
             p("\ - Date: March 24, 2021: \"You can now buy a Tesla with Bitcoin\" SC = .00"),
             p("\ - Date: March 24, 2021: \"Pay by Bitcoin capability available outside US later this year\" SC = .41"),
             p("\ - Date: March 24, 2021: \"Tesla is using only internal &amp; open source software &amp; operates Bitcoin nodes directly. Bitcoin paid to Tesla will be retained as Bitcoin, not converted to fiat currency\"SC = .12"),
             p("\ - Date: April 27, 2021: \"@stoolpresidente No, you do not. I have not sold any of my Bitcoin. Tesla sold 10% of its holdings essentially to prove liquidity of Bitcoin as an alternative to holding cash on balance sheet.\" SC = .17"),
             p("\ - Date: May 14, 2021: \"To be clear, I strongly believe in crypto, but it can’t drive a massive increase in fossil fuel use, especially coal\" SC = .56"),
             h5(strong("Negative Tweets:")),
             p("\ - Date: February 21, 2021: \"Heard a rumor some crypto coin was pegging the dollar 🤣🤣\" SC= -.07"),
             p("\ - Date: February 21, 2021: \"Cryptocurrency explained https://t.co/kUXaXx8a1R\" SC= .00"),
             p("\ - Date: November 20, 2021: \"@WSBChairman Bitcoin cures cancer\"SC= -.38"),
             h5(strong("Neutral Tweets:")),
             p("\ - Date: February 10, 2021: \"@freewalletorg Any crypto wallet that won’t give you your private keys should be avoided at all costs\" SC = .00"),
             br(),
             br(),
             br(),
             dateRangeInput('selectDate2', 
                            'Select date', 
                            start = min('2014-09-17'), 
                            end = max('2022-03-25')),
             checkboxInput("logInput3", "Plot y axis on log scale", value = FALSE),
             h4(strong("Conclusion")),
             p("\ - despite an increase in the tweet volume about Bitcoin in 2021 and the correlation between tweets and Bitcoin price,
               there is no apparent impact on price, therefore, tweet sentiment is not a good predictor of Bitcoin price"),
             h4(strong("Recommendation")),
             p("\ - Date: May 7, 2021: \"Cryptocurrency is promising, but please invest with caution! https://t.co/A4kplcP8Vq\""),
             p("\ - take into account other variables such as the state of the economy, the industry as a whole"),
             h4(strong("Future Work")),
             p("\ - conduct further research on what variables can potentially impact the fluctuations in price")
             
            ),
           mainPanel(dygraphOutput("ElonMuskTweets",height = "500px"))
          )
      )
 )

 
 

# Define server logic required to draw a histogram
server <- function(input, output) {
  
  getData <- reactive({
    
    # get inputs 
    selectedOutput <- input$selectOutput
    startDate <- input$selectDate[1]
    endDate <- input$selectDate[2]
    
    
    # filter data
    data <- bitcoin %>%
      select(Date, selectedOutput) %>%
      filter(Date >= startDate & Date <= endDate)
    
    
    # formatting in case of market cap
    if(selectedOutput == "Volume"){
      data["Volume"] <- lapply(data["Volume"], FUN = function(x) x/1000000000)
    }
    
    
    # converting to logscale for bitcoin price
    if(input$logInput == TRUE & input$selectOutput != "Volume"){
      data[selectedOutput] = log(data[selectedOutput])
      
    }
    
    data
  })
  
  output$priceGraph <- renderDygraph({
    data <- getData()
    time_series <- xts(data, order.by = data$Date)
    dygraph(time_series)
  })
  
  
  
  output$BitcoinForecast <- renderDygraph({
    columns_to_select <- append("Date", input$selectVariable)
    data <- bitcoin[,columns_to_select]
    
    if(input$logInput2 == TRUE) {
      data[input$selectVariable] = log(data[input$selectVariable])}
    
    colnames(data) <- c("ds","y")
    
    #Create dygraph
    m <- prophet(data)
    
    #Create future dates
    future <- make_future_dataframe(m, periods = input$selectHorizon)
    
    #Create Forecast
    forecast <- predict(m, future)
    
    dyplot.prophet(m, forecast)
  })
  
  output$gmplot <- renderPlot({
    
    
    p1 <- ggplot(freq_per_year, aes(x = year, y = frequency,  color = frequency)) + 
    theme(plot.title = element_text(face="bold", hjust = 0.5), axis.title = element_text(face="bold"))+
    geom_line()+ggtitle("Tweet Count 2010 - 2021") 
    
  
    p2 <- ggplot(replies_count, aes(x=year, y=Freq_of_replies, fill=Freq_of_replies)) +
    geom_bar(stat="identity")+theme(plot.title = element_text(face="bold", hjust = 0.5), axis.title = element_text(face="bold")) + 
    scale_y_continuous(name="Frequencies of replies")+ ggtitle("Replies Per Year")
    

    p3 <- ggplot(retweet_count, aes(x=year, y=Freq_of_retweets, fill=Freq_of_retweets)) +
    geom_bar(stat="identity")+theme(plot.title = element_text(face="bold", hjust = 0.5), axis.title = element_text(face="bold")) +
    scale_y_continuous(name="Frequencies of retweets") + ggtitle("Retweets Per Year")
    

    p4<- ggplot(likes_count, aes(x=year, y=Freq_of_likes/1000000, fill=Freq_of_likes)) +
    geom_bar(stat="identity")+theme(plot.title = element_text(face="bold", hjust = 0.5), axis.title = element_text(face="bold")) + 
    scale_y_continuous(name="Frequencies of likes") + ggtitle("Likes Per Year")
    
  
    
    grid.arrange(p1,p2,p3,p4)
    
  }) 
  

  
  
  
  output$ElonMuskTweets <- renderDygraph({
    
    #get inputs
    startDate2 <- input$selectDate2[1]
    endDate2 <- input$selectDate2[2]
    
    
    # format data
    close_price <- xts(x = bitcoin$Close, order.by = bitcoin$Date)
    positive_tweet <- xts(x = bitcoin_tweets_positive$Close, order.by = bitcoin_tweets_positive$Date)
    negative_tweet <- xts(x = bitcoin_tweets_negative$Close, order.by = bitcoin_tweets_negative$Date)
    neutral_tweet <- xts(x = bitcoin_tweets_neutral$Close, order.by = bitcoin_tweets_neutral$Date)
    prices <- cbind(close_price, positive_tweet, negative_tweet, neutral_tweet)
    
   
    
  
    
    if(input$logInput3 == TRUE) {
      prices = log(prices)
      
      }
    
    
    dygraph(prices) %>%
      dyRangeSelector(dateWindow= c(startDate2, endDate2)) %>%
      dySeries("close_price", label = "Bitcoin price") %>%
      dySeries("positive_tweet", label = "Positive tweets", drawPoints = TRUE, pointSize = 3, color = "green") %>%
      dySeries("negative_tweet", label = "Negative tweets", drawPoints = TRUE, pointSize = 3, color = "red") %>%
      dySeries("neutral_tweet", label = "Neutral tweets", drawPoints = TRUE, pointSize = 3, color = "blue") %>%
      dyRangeSelector()
  })
  
  
}
# Run the application 
shinyApp(ui = ui, server = server)

